name = "vibes-testyourvibes-com"
main = "worker.js"
compatibility_date = "2026-02-24"
routes = [
  { pattern = "testyourvibes.com/*", zone_name = "testyourvibes.com" },
  { pattern = "www.testyourvibes.com/*", zone_name = "testyourvibes.com" }
]

[assets]
directory = "../../www/testyourvibes.com"
binding = "ASSETS"
